### ISSUE TITLE
KiteSublime suppresses GitGutter gutter popup

### ISSUE THREAD

**Issue by pykong** [kiteco/KiteSublime#50]
It appears `KiteSublime` is interfering with `GitGutter`, which is one of the most used plugins for SublimeText. This is a critical error, as many developers critically rely on GitGutter.

The error is that when the `KiteSublime` plugin is active it totally prevents the opening of the `GitGutter` popup on hovering the gutter.

Interestingly an issue which prevented the gutter hover for a different plugin `SublimeLinter` has been fixed. See: https://github.com/kiteco/KiteSublime/issues/46

**Versions:**
Sublime Text 3: 3208
Kite engine: 2.20190423.1
KiteSublime: ? (appears up-to-date)

Platform: Linux Mint 19.x

**Comment by its-dhung** [comment]
Hey @pykong, thanks for reporting this. This should have been fixed already by #48. Can you make sure you have the latest version of this package and see if this behavior persists? You may need to close Sublime, uninstall and reinstall the package to get it updated.

**Comment by pykong** [comment]
Negative. The problem described still persists for me.

#48 Indeed solved the hovering issue for `SublimeLinter` but `GitGutter` and possibly other yet to be identified plugins are also affected.

I have manually removed `KiteSublime` and reinstalled from CodePilot.
I have also tried to use the most recent `KiteSublime.py` file directly from GitHub.

But to no avail. There is an issue for me.
I am going to check if I can reproduce the issue on my `Mac`.

Is my Kite engine up to date?

**Comment by pykong** [comment]
With `KiteSublime` active:

![image](https://user-images.githubusercontent.com/20211140/59538283-799f6180-8ef9-11e9-9c34-3929cc9a4dbf.png)

With `KiteSublime` disabled: 
![image](https://user-images.githubusercontent.com/20211140/59538340-afdce100-8ef9-11e9-8155-12e654682a24.png)
_(GitGutter popup clearly shown.)_

**Comment by jansorg** [comment]
@pykong @its-dhung I can confirm that KiteSublime is blocking the gutter display of GitGutter.
This is the line interfering with the popup: https://github.com/kiteco/KiteSublime/blob/d351f6c185a6bfe254acdb26fce6ce4bb0f4b64a/lib/handlers.py#L123

My guess is that GitGutter (or Sublime) triggers a `selection` command which then hides any popup which is visible or being processed at that time.

**Comment by pykong** [comment]
Thanks for the quick fix. When will the new version of `KiteSublime` get released?

**Comment by jansorg** [comment]
@pykong Tonight if nothing unexpected happens during release and qa.

**Comment by pykong** [comment]
Great. Looking forward to it.

**Comment by pykong** [comment]
I can confirm that after updating `KiteSublime` today the issue has been fixed.
